### ISSUE TITLE
Add success message after loading patterns

### ISSUE THREAD

**Issue by emdio** [db3108/michi-c2#10]
Hope this doesn't feel "picky", but since michi-c2 sends a message when no patterns are loaded, maybe it'd be a good idea to print out a "successfully loaded patterns" message when it's done.
Not important, of course, but when you add and  the pattern files and run "./michi gtp" again it shows nothing at all, so you are not sure whether it's worked, or the program is still loading the info (in some engines, like pachi, it takes quite a while).

**Comment by db3108** [comment]
Emilio,

Thanks for your proposal, but I don't agree. Following UNIX philosophy, when a program has nothing to say, then it must be silent.
Writing nothing, means that everything is OK. Then, when something goes wrong the warning or error message is not buried under tons of non informative messages on the console.

In addition, michi-c is not intended to be played in a text console using the gtp protocol. Normally we use gogui or another gtp interface to play with it. So you can see when the initialization is finished (there are a lot of commands coming from the gtp interface that are executed after the initialization and you see the answers in the gtp console). In your case, if you are in doubt, you can send a command like name or version and michi will respond instantaneously if it is ready.

As a third point, loading the pattern files does take only a couple of seconds and it is a constant time,
so the user knows what happens after playing only a small number of times with michi.

By the way, you find the information that the patterns have been successfully loaded in the log file michi.log (which is updated in real time, there is no buffering). I think this is sufficient.

Please don't declare that as an issue. This a feature and it's important for me to keep going with the philosophy described above.
