### ISSUE TITLE
Muller and 1D

### ISSUE THREAD

**Issue by gonmf** [db3108/michi-c2#15]
Hello, in https://github.com/db3108/michi-c2/blob/master/board.c the header commentary mentions Müller 2002, is it about "Counting the Score: Position Evaluation in Computer Go"? I can't find a definition of 1D there.

**Comment by db3108** [comment]
Hello,
No, this is not this one. The correct ref is in the header file of michi.c (with a few others).
You can download it at https://webdocs.cs.ualberta.ca/~mmueller/publications.html#2002
Denis
