### ISSUE TITLE
Bug about board size on gogui?

### ISSUE THREAD

**Issue by emdio** [db3108/michi-c2#3]
Today (2015-09-06) I made a pull of michi-c2. I compiled without issues, but after trying to load michi-c2 on gogui I got a message related to the board size.
![michi_c2_bug](https://cloud.githubusercontent.com/assets/1314942/9703376/cde599ea-5482-11e5-8d42-4482c1bf934a.png)

The content of michi.log:
$ cat michi.log 
I     0/000 michi-c Version 1.4
I     0/000 size of struct Position = 5252 bytes
I     0/000 size of struct TreeNode = 40 bytes
I     0/000 size of int  = 4 bytes
I     0/000 size of long = 8 bytes
T     0/000 time          :  nsims seconds  sims/s moves tleft
S     0/000 search: idum dkomi 1st (2nd) best2  bestr bestwr games/s
I     0/000 Loading pattern probs ...
I     0/000 Loading pattern spatial dictionary ...
I     0/000 read 1064481 patterns
I     0/000 idmax = 1064481
I     0/000 pattern length max = 141 (found at 1064481)
I     0/000 =========== Hashtable initialization synthesis ==========
I     0/000 hashtable entries: 8483962 (fill ratio: 25.3 %)
I     0/000 8515848 searches, 31886 success (0.4 %)
I     0/000 average length of searchs -- success: 1.7, failure: 2.9
C     0/000 name
C     0/000 protocol_version
C     0/000 version
C     0/000 list_commands
C     0/000 gogui-analyze_commands
C     0/000 boardsize 19
W     0/000 Error: Trying to set incompatible boardsize 19 (max=13)
C     0/000 quit
I     0/000 hashtable entries: 8483962 (fill ratio: 25.3 %)
I     0/000 0 searches, 0 success (-nan %)
I     0/000 average length of searchs -- success: -nan, failure: -nan

**Comment by emdio** [comment]
Ok, it seems that just setting "#define N" to 19 in board.h solved the bug.

**Comment by db3108** [comment]
On 06/09/2015 10:47, Emilio wrote:

> Ok, it seems that just setting "#define N" to 19 in board.h solved the 
> bug.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/db3108/michi-c2/issues/3#issuecomment-138057990.
> 
> I Emilio,

Yes, you solved it.

Sorry
1. to have put the 13x13 version of board.h on GitHub. Hope that you did 
not waste to much time because of this.
2. for the delay in responding. I just come back from a 4 days trip, and 
see your message only this evening.

Hope also that you enjoy playing michi-c or trying to improve it. As 
Petr Baudis noticed there is much room for experimentations and 
improvements.

Best,

Denis

**Comment by emdio** [comment]
The fixing was pretty trivial (actually it hardly deserved to be called a bug), so was able to solve it quite fast.

I have some experience programming chess engines, and I feel tempted to start something on go (michi-c seems like a nice opportunity for it), but other than a general idea of how the MCTS engines work, I lack all the knowledge on how these guys work.
