### ISSUE TITLE
test fails on OS X (El Capitan)

### ISSUE THREAD

**Issue by y-ich** [db3108/michi-c2#4]
hi.

I just did 'make' and 'make test' on OS X and the test failed with errors "net.sf.gogui.tools.regress.Regress$ProgramIsDeadException:"

A version of My GoGui is 1.4.9.

It may be OS X specific. Just for your information.

**Comment by db3108** [comment]
On 10/11/2015 10:29, y-ich wrote:

> hi.
> 
> I just did 'make' and 'make test' on OS X and the test failed with 
> errors "net.sf.gogui.tools.regress.Regress$ProgramIsDeadException:"
> 
> A version of My GoGui is 1.4.9.
> 
> It may be OS X specific. Just for your information.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/db3108/michi-c2/issues/4.
> 
> Hi,

Thank you for your feedback.

I hope to have access to a Mac OS X in the next few days.
I will try to repeat your experiment and understand what happens.
I will come back to you with the results, ... and maybe hope for your 
help, if I can't reproduce your results.

Best,
Denis

**Comment by emdio** [comment]
It seems the issue has to do with the file "tests/run", in the line where defines the path to gogui;
if [ "$GOGUI" == "" ]; then
    export GOGUI="$HOME/prg/go/gogui-1.4.9/bin"
fi

I'd suggest, as a quick fix, to define GOGUI for your own system.
In a linux environment using the command "which" to find out the path to gogui (if installed) can be of help.

**Comment by db3108** [comment]
On 10/11/2015 21:03, Emilio wrote:

> It seems the issue has to do with the file "tests/run", in the line 
> where defines the path to gogui;
> if [ "$GOGUI" == "" ]; then
> export GOGUI="$HOME/prg/go/gogui-1.4.9/bin"
> fi
> 
> I'd suggest, as a quick fix, to define GOGUI for your own system.
> In a linux environment using the command "which" to find out the path 
> to gogui (if installed) can be of help.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/db3108/michi-c2/issues/4#issuecomment-155549955.
> 
> Thanks emilio,

This is not a quick fix, this is a requirement.
If you do do not specify what is the path to your own gogui executable, 
michi-c cannot guess it. ... Maybe somebody have a better solution.

Best,
Denis
