### ISSUE TITLE
test_michi failed.

### ISSUE THREAD

**Issue by y-ich** [db3108/michi-c2#5]
The commit 7882c3c87a67c52c2947ae566939bf69dd2f7e96 made test_michi failed even if N is changed to 19.
Maybe needs to update test/ref/*.txt.

**Comment by db3108** [comment]
Hi y-ich,

Thank you for your thorough analysis of michi-c2. 

I can't understand your report. I've just run 
make test 
from a fresh clone retrieved from GitHub with N=19 and N=13. The 2 cases worked fine.
My platform is Linux UBUNTU 12.04 with gcc 4.6.3
Could you please be more specific about what is wrong ? 
Maybe by attaching the result of 
make test_verbose
on your system, as well with a brief description of what your system is (Mac, Windows, Linux ? which version of gogui ? Did you define the GOGUI variable ... which is necessary for the test to work ?)

Best,
Denis

**Comment by y-ich** [comment]
Here is the result of make test_verbose, but in my understanding, test/test_verbose and test_michi are completely different and I am talking about test_michi.

result of make test_verbose on OS X 10.11.1 and GoGui 1.4.9
(This is the one that I reported in another issue, and I surely define GOGUI, otherwise, no one outputs "net.sf.gogui.tools.regress.Regress$ProgramIsDeadException")
tests/run -long
10 passed
20 passed
30 passed
110 passed
net.sf.gogui.tools.regress.Regress$ProgramIsDeadException:
Program died
10 passed
20 passed
30 passed
net.sf.gogui.tools.regress.Regress$ProgramIsDeadException:
Program died
10 passed
20 passed
30 passed
110 passed
120 passed
130 passed
140 passed
210 passed
220 passed
230 passed
net.sf.gogui.tools.regress.Regress$ProgramIsDeadException:
Program died
110 passed
120 passed
130 passed
140 passed
210 passed
220 passed
230 passed
310 passed
320 passed
320 passed
410 passed
420 passed
430 passed
431 passed
432 passed
440 passed
441 passed
442 passed
450 passed
net.sf.gogui.tools.regress.Regress$ProgramIsDeadException:
Program died

**Comment by db3108** [comment]
Thank you.
And sorry, I misread your first comment. It was indeed correct. I have updated the ref files.

What surprises me however are the 4 occurrences of "Program died" in your result of make test_verbose

Best,
Denis
