### ISSUE TITLE
Size of probs may be wrong.

### ISSUE THREAD

**Issue by y-ich** [db3108/michi-c2#6]
The line 615 in patterns.c calloc probs with 1064481, but should be with more than 1064481.
Because patterns.prob includes (s: 1064481).

**Comment by db3108** [comment]
Hi y-ich,

Thank you again. Yes, you are right. 
I hope that the changes that I've just committed solved the problem and also make michi-c2 more robust to a potential change of the patterns file by Petr Baudis.

Best,
Denis
